<?php
declare(strict_types=1);

// Shared factual copy for fresh installations and the explicit content update tool.
const PUBLIC_SITE_COPY = [
    'hero_eyebrow'=>'Avukatlık ve hukuki danışmanlık',
    'hero_title'=>'Yurtdaş Hukuk',
    'hero_image'=>'/assets/images/law-hero-light-v1.webp',
    'hero_image_alt'=>'Hukuk kitapları, terazi ve tokmak temalı görsel',
    'hero_text'=>'Av. Halil İbrahim Yurtdaş. Antakya, Hatay.',
    'hero_button'=>'Avukat hakkında',
    'hero_button_url'=>'/avukatlar/halil-ibrahim-yurtdas',
    'hero_secondary'=>'Çalışma alanları',
    'hero_note'=>'',
    'intro_eyebrow'=>'Büro hakkında',
    'intro_title'=>'Yurtdaş Hukuk',
    'intro_text'=>"Yurtdaş Hukuk, Av. Halil İbrahim Yurtdaş tarafından Antakya, Hatay’da yürütülen avukatlık ve hukuki danışmanlık faaliyetinin büro adıdır.\n\nÇalışmanın kapsamı; ilgili belgeler, işlem tarihleri ve somut olayın koşulları değerlendirilerek belirlenir. Görüşmeler randevu ile yapılır.",
    'intro_image'=>'/assets/images/law-about-study-v1.webp',
    'intro_image_alt'=>'Açık hukuk kitabı ve pirinç terazi içeren temsili çalışma masası',
    'intro_caption'=>'Avukatlık ve hukuki danışmanlık',
    'approach_eyebrow'=>'Çalışma usulü',
    'approach_title'=>'Belge incelemesi ve hukuki değerlendirme',
    'approach_text'=>'Başvurunun konusu, ilgili belgeler ve işlem tarihleri değerlendirilir. Çalışmanın kapsamı ile iletişim yöntemi ayrıca belirlenir. Hukuki sonuçlar her dosyanın koşullarına göre değişir.',
    'office_eyebrow'=>'Büro bilgileri',
    'office_title'=>'Görüşme ve iletişim',
    'office_text'=>'Görüşmeler randevu ile yapılır. Telefon, e-posta ve büro adresi iletişim sayfasında yer alır.',
    'practice_eyebrow'=>'Mesleki faaliyet',
    'practice_title'=>'Çalışma alanları',
    'practice_text'=>'Büronun faaliyet gösterdiği hukuk alanları aşağıda yer alır. Bu bilgiler uzmanlık veya sonuç taahhüdü anlamına gelmez.',
    'articles_eyebrow'=>'Hukuki yayınlar',
    'articles_title'=>'Makaleler',
    'articles_text'=>'Genel bilgilendirme amacıyla hazırlanmış hukuki yazılar. Yayınlar, somut bir olay için hukuki görüş veya danışmanlık yerine geçmez.',
    'contact_eyebrow'=>'Büro iletişimi',
    'contact_title'=>'İletişim bilgileri',
    'contact_text'=>'Büro adresi, çalışma saatleri ve iletişim kanalları. Görüşmeler randevu ile yapılır.',
    'contact_button'=>'İletişim bilgileri',
    'home_profile_eyebrow'=>'Kurucu avukat',
    'home_profile_title'=>'Kurucu avukat',
    'home_profile_text'=>'Mesleki bilgiler, biyografi ve yayımlanmış hukuki yazılar.',
    'home_map_eyebrow'=>'Adres',
    'home_map_title'=>'Büro konumu',
    'district'=>'Antakya',
    'sitemap_enabled'=>'1',
    'logo_mark'=>'',
    'hero_title_size'=>'80',
    'mobile_hero_title_size'=>'44',
    'seo_service_area'=>'Antakya, Hatay',
    'seo_title'=>'Av. Halil İbrahim Yurtdaş | Antakya, Hatay | Yurtdaş Hukuk',
    'seo_description'=>'Antakya, Hatay’da Yurtdaş Hukuk ve Av. Halil İbrahim Yurtdaş: mesleki bilgiler, çalışma alanları, hukuki yayınlar, büro adresi ve randevu iletişimi.',
    'geo_summary'=>'Yurtdaş Hukuk, Av. Halil İbrahim Yurtdaş’ın Antakya, Hatay’daki avukatlık ve hukuki danışmanlık bürosudur. Büro adresi Küçükdalyan, A Plaza, Antakya/Hatay’dır. Görüşmeler randevu ile yapılır.',
    'footer_text'=>'',
    'primary_color'=>'#204a43',
    'action_color'=>'#28584f',
    'accent_color'=>'#947447',
    'background_color'=>'#f3f6f5',
    'surface_color'=>'#ffffff',
    'text_color'=>'#253238',
    'muted_color'=>'#59666a',
    'border_color'=>'#dbe3df',
    'header_color'=>'#ffffff',
    'header_text_color'=>'#253238',
    'footer_color'=>'#eef3f0',
    'footer_text_color'=>'#354940',
    'dark_section_color'=>'#eef3f0',
    'dark_section_text_color'=>'#253238',
    'heading_font'=>'classic',
    'hero_height'=>'550',
    'hero_overlay_color'=>'#ffffff',
    'hero_overlay_opacity'=>'10',
    'hero_text_color'=>'#172c35',
    'card_radius'=>'4',
    'show_topbar'=>'0',
    'show_header_contact'=>'0',
    'show_floating_contact'=>'0',
    'show_principles'=>'0',
    'show_intro'=>'1',
    'show_approach'=>'0',
    'show_office'=>'0',
    'show_contact'=>'0',
    'show_home_contacts'=>'1',
    'show_home_consultation'=>'0',
    'home_articles_layout'=>'grid',
    'home_article_count'=>'3',
    'home_section_order'=>'intro,home_profile,practices,articles,faq,home_map,home_consultation,principles,approach,office,contact',
    'text_faq_title'=>'Sıkça sorulan sorular',
    'text_practice_archive_title'=>'Çalışma alanları',
    'text_contact_page_title'=>'İletişim',
    'text_contact_info_title'=>'Büro iletişimi',
    'text_contact_info_text'=>'Büro adresi, telefon ve çalışma saatleri aşağıda yer alır. Görüşmeler randevu ile yapılır.',
    'text_contact_form_title'=>'Görüşme talebi',
    'text_contact_notice_agreement'=>'İletişim formuna ilişkin aydınlatma metni',
    'text_hub_card_text'=>'{kategori} alanındaki yayımlanmış yazılar.',
    'text_sidebar_title'=>'Büro iletişimi',
    'text_sidebar_text'=>'Adres ve iletişim bilgileri.',
    'text_search_title'=>'Makalelerde ara',
    'text_search_help'=>'',
];

const PUBLIC_PROFILE_EXCERPT = 'Halil İbrahim Yurtdaş, Yurtdaş Hukuk bünyesinde avukatlık ve hukuki danışmanlık faaliyeti yürütür.';
const PUBLIC_PROFILE_BODY = "Halil İbrahim Yurtdaş, Yurtdaş Hukuk bünyesinde avukatlık ve hukuki danışmanlık faaliyeti yürütür.\n\nMesleki faaliyet alanları aile, ceza, iş, ticaret ve şirketler, gayrimenkul ve miras hukukunu kapsar. Çalışma alanlarının belirtilmesi uzmanlık unvanı anlamına gelmez.\n\nHukuki incelemede somut olayın koşulları, ilgili belgeler ve yürürlükteki düzenlemeler dikkate alınır. Görüşmeler randevu ile yapılır; çalışma kapsamı ayrıca belirlenir.";
const PUBLIC_CORPORATE_EXCERPT = 'Yurtdaş Hukuk, Av. Halil İbrahim Yurtdaş tarafından Antakya, Hatay’da yürütülen avukatlık ve hukuki danışmanlık faaliyetine ilişkin büro adıdır.';
const PUBLIC_CORPORATE_BODY = "## Büro hakkında\nYurtdaş Hukuk bünyesinde avukatlık ve hukuki danışmanlık faaliyeti yürütülür. Avukatın mesleki bilgileri ve yayımlanmış yazıları avukat profili sayfasında yer alır.\n\n## Çalışma alanları\nFaaliyet alanları aile, ceza, iş, ticaret ve şirketler, gayrimenkul ve miras hukukunu kapsar. Çalışma alanlarının belirtilmesi uzmanlık unvanı veya sonuç taahhüdü anlamına gelmez.\n\n## Görüşme usulü\nGörüşmeler randevu ile yapılır. İlgili belgeler ve somut olayın koşulları değerlendirilerek çalışmanın kapsamı ayrıca belirlenir.\n\n## Mesleki yükümlülükler\nAvukatlık faaliyeti, yürürlükteki mevzuat ve meslek kuralları çerçevesinde yürütülür. Mesleki sır ve kişisel verilerin korunmasına ilişkin yükümlülükler gözetilir.";
const PUBLIC_APPOINTMENT_ANSWER = 'Görüşme zamanı için iletişim sayfasındaki büro telefonunu kullanabilirsiniz. İletişim formu kullanıma açıksa görüşmek istediğiniz konuyu ve iletişim bilgilerinizi bu yolla da iletebilirsiniz. Görüşmeler randevu ile yapılır.';
const PUBLIC_NAVIGATION_NOTICE = "## Sayfa geçişleri\nSayfalar arasındaki kısa görsel geçiş için tarayıcının sekmeye özel sessionStorage alanına hukuk-page-navigation anahtarıyla gidilecek site içi adres ve işlem zamanı geçici olarak yazılır. Kayıt en fazla 10 saniye boyunca geçerlidir; hedef sayfada silinir. Geçiş iptal edilip aynı sayfada kalınırsa 10 saniye sonra temizlenir. Sekme kapatıldığında tarayıcı tarafından kaldırılır. Bu kayıt sunucuya veya üçüncü taraflara gönderilmez ve ziyaretçi profili oluşturmak için kullanılmaz. Tarayıcı depolaması engellense veya hareket azaltma tercihi seçilse de bağlantılar çalışır.";
const PUBLIC_COOKIE_BODY = "## Oturum çerezi\nBu site, formların güvenliği ve yönetim paneli oturumu için hukuk_session adlı bir oturum çerezi kullanır. Çerez, oturum kimliğini içerir ve tarayıcı oturumuyla sınırlıdır.\n\n## Analitik ve reklam\nVarsayılan kurulumda analitik veya reklam amaçlı çerez kullanılmaz. Siteye yeni hizmetler eklenmesi durumunda bu metin güncellenmelidir.\n\n## Harita ve harici bağlantılar\nGömülü Google haritası sayfa açılışında yüklenmez. Haritayı gösterme düğmesine basıldığında tarayıcınız Google sunucularıyla bağlantı kurar. Harita hizmeti, üçüncü tarafın çerez ve veri işleme uygulamalarına tabidir. Yol tarifi ve WhatsApp bağlantıları da ilgili harici hizmeti açar. Bu hizmetlerin veri işleme koşulları kendi [Google gizlilik politikası](https://policies.google.com/privacy) ve [WhatsApp gizlilik politikası](https://www.whatsapp.com/legal/privacy-policy) sayfalarında açıklanır.\n\n## Tarayıcı tercihleri\nÇerezleri tarayıcınızın ayarlarından yönetebilirsiniz. Oturum çerezlerinin engellenmesi, iletişim formu veya yönetim panelinin çalışmasını etkileyebilir." . "\n\n" . PUBLIC_NAVIGATION_NOTICE;

const PUBLIC_PRACTICE_COPY = [
    'aile-hukuku'=>[
        'image'=>'/assets/images/practice/aile-hukuku.jpg',
        'excerpt'=>'Boşanma, velayet, nafaka ve mal rejimine ilişkin hukuki meseleler.',
        'intro'=>'Aile hukuku, aile ilişkilerinden doğan hak ve yükümlülükleri konu alır. İnceleme, tarafların durumu ve ilgili belgeler üzerinden yapılır.',
        'topics'=>['Boşanma ve ayrılık','Velayet ve kişisel ilişki','Nafaka','Mal rejimi ve malvarlığı uyuşmazlıkları'],
    ],
    'ceza-hukuku'=>[
        'image'=>'/assets/images/practice/ceza-hukuku.jpg',
        'excerpt'=>'Soruşturma ve kovuşturma aşamalarında hukuki yardım ve temsil.',
        'intro'=>'Ceza hukuku kapsamındaki işlemler, kişinin dosyadaki sıfatına ve sürecin aşamasına göre değerlendirilir. Dosya incelemesi, deliller ve usule ilişkin haklar birlikte ele alınır.',
        'topics'=>['Soruşturma işlemleri','Ceza yargılaması','Şüpheli, sanık ve mağdur hakları','Kanun yolu incelemeleri'],
    ],
    'is-hukuku'=>[
        'image'=>'/assets/images/practice/is-hukuku.jpg',
        'excerpt'=>'İş sözleşmeleri, iş ilişkisinin sona ermesi ve çalışma hayatındaki uyuşmazlıklar.',
        'intro'=>'İş hukuku, işçi ve işveren arasındaki ilişkiyi konu alır. Sözleşmeler, çalışma kayıtları ve bildirimler somut uyuşmazlık kapsamında değerlendirilir.',
        'topics'=>['İş sözleşmelerinin incelenmesi','Fesih ve işe iade','İşçilik alacakları','Uyuşmazlığa uygun arabuluculuk ve yargılama işlemleri'],
    ],
    'ticaret-ve-sirketler-hukuku'=>[
        'image'=>'/assets/images/practice/ticaret-sirketler-hukuku.jpg',
        'excerpt'=>'Ticari sözleşmeler, şirket işlemleri ve ortaklık ilişkileri.',
        'intro'=>'Ticaret ve şirketler hukuku kapsamındaki inceleme, ticari işlemin niteliğine ve şirketin hukuki yapısına göre yapılır.',
        'topics'=>['Şirket kuruluşu ve kurumsal işlemler','Ticari sözleşmeler','Ortaklık ilişkileri','Ticari alacak ve uyuşmazlıklar'],
    ],
    'gayrimenkul-hukuku'=>[
        'image'=>'/assets/images/practice/gayrimenkul-hukuku.jpg',
        'excerpt'=>'Mülkiyet, tapu, kira ve kat mülkiyetine ilişkin hukuki meseleler.',
        'intro'=>'Gayrimenkule ilişkin incelemede tapu kayıtları, sözleşmeler, tarafların sıfatları ve taşınmazın hukuki durumu dikkate alınır.',
        'topics'=>['Tapu ve mülkiyet uyuşmazlıkları','Kira ilişkileri','Kat mülkiyeti','Taşınmaz sözleşmeleri'],
    ],
    'miras-hukuku'=>[
        'image'=>'/assets/images/practice/miras-hukuku.jpg',
        'excerpt'=>'Mirasçılık, mirasın paylaşılması ve ölüme bağlı tasarruflar.',
        'intro'=>'Miras hukuku kapsamındaki değerlendirme, mirasçıların durumu, terekeye ilişkin bilgiler ve ilgili belgeler üzerinden yapılır.',
        'topics'=>['Mirasçılık belgesi','Miras paylaşımı','Vasiyetname ve diğer ölüme bağlı tasarruflar','Miras kaynaklı uyuşmazlıklar'],
    ],
];

function public_practice_body(array $copy): string {
    return "## Kapsam\n".$copy['intro']."\n\n## İlgili konular\n- ".implode("\n- ",$copy['topics'])."\n\n## Bilgilendirme\nBu sayfa büronun çalışma alanını açıklamak amacıyla hazırlanmıştır. Uzmanlık veya sonuç taahhüdü içermez. Süreler, başvuru koşulları ve izlenebilecek hukuki yollar somut olayın koşullarına göre ayrıca değerlendirilir.";
}
