<?php
declare(strict_types=1);

// Local-only secrets. On Vercel these values come from project environment settings.
if(!getenv('VERCEL')&&is_file(dirname(__DIR__).'/.env.local')){
    foreach(file(dirname(__DIR__).'/.env.local',FILE_IGNORE_NEW_LINES) as $line){
        if(!preg_match('/^(HUKUK_[A-Z0-9_]+)=(.*)$/',$line,$m)||getenv($m[1])!==false)continue;
        $value=trim($m[2]);if(strlen($value)>=2&&in_array($value[0],['"',"'"],true)&&$value[0]===substr($value,-1))$value=substr($value,1,-1);
        putenv($m[1].'='.$value);
    }
}
function cloud_database(): bool {return (string)getenv('HUKUK_DATABASE_URL')!=='';}
function vercel_runtime(): bool {return getenv('VERCEL')==='1';}
function upload_limit(): int {return vercel_runtime()?3*1024*1024:5*1024*1024;}
function backup_upload_limit(): int {return vercel_runtime()?3*1024*1024:10*1024*1024;}
function database_connection(): PDO {
    $options=[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC];
    if(!cloud_database()){
        if(vercel_runtime())throw new RuntimeException('Vercel için kalıcı veritabanı ayarlanmamış.');
        $pdo=new PDO('sqlite:'.DATA_DIR.'/site.sqlite',null,null,$options);
        $pdo->exec('PRAGMA journal_mode=WAL; PRAGMA busy_timeout=5000; PRAGMA foreign_keys=ON;');return $pdo;
    }
    $parts=parse_url((string)getenv('HUKUK_DATABASE_URL'));
    if(!$parts||!in_array($parts['scheme']??'',['postgres','postgresql'],true)||empty($parts['host'])||empty($parts['user']))throw new RuntimeException('PostgreSQL bağlantı ayarı geçersiz.');
    $host=$parts['host'];$name=ltrim($parts['path']??'/postgres','/');$user=rawurldecode($parts['user']);
    foreach([$host,$name,$user] as $part)if(preg_match('/[;\x00-\x20]/',$part))throw new RuntimeException('Veritabanı bağlantı bileşeni geçersiz.');
    $local=in_array($host,['127.0.0.1','localhost','[::1]'],true)&&!vercel_runtime();
    $ssl=$local?'disable':'require';
    $pdo=new PDO('pgsql:host='.$host.';port='.(int)($parts['port']??5432).';dbname='.$name.';sslmode='.$ssl.';connect_timeout=10',$user,rawurldecode($parts['pass']??''),$options+[PDO::ATTR_EMULATE_PREPARES=>true]);
    $pdo->exec("SET search_path TO hukuk; SET TIME ZONE 'Europe/Istanbul'; SET statement_timeout TO '15s'");return $pdo;
}
function initialize_database(PDO $db): void {
    $sql=file_get_contents(__DIR__.'/schema.sql');
    if($db->getAttribute(PDO::ATTR_DRIVER_NAME)==='pgsql'){
        $db->exec('CREATE SCHEMA IF NOT EXISTS hukuk');
        $sql=str_replace('INTEGER PRIMARY KEY AUTOINCREMENT','BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY',$sql);
    }
    $db->exec($sql);
}
function migrate_entry_presentation(PDO $db): void {
    $db->exec('CREATE TABLE IF NOT EXISTS entry_redirects (type TEXT NOT NULL, slug TEXT NOT NULL, entry_id BIGINT NOT NULL, PRIMARY KEY(type,slug))');
    $identity=$db->getAttribute(PDO::ATTR_DRIVER_NAME)==='pgsql'?'BIGINT GENERATED BY DEFAULT AS IDENTITY':'INTEGER';
    $db->exec("CREATE TABLE IF NOT EXISTS url_redirects (id $identity PRIMARY KEY, source_path TEXT NOT NULL UNIQUE, target_path TEXT NOT NULL, status_code INTEGER NOT NULL DEFAULT 301, enabled INTEGER NOT NULL DEFAULT 1, updated_at TEXT NOT NULL)");
    $db->exec("CREATE TABLE IF NOT EXISTS seo_urls (path TEXT PRIMARY KEY, sitemap_enabled INTEGER NOT NULL DEFAULT 1, noindex INTEGER NOT NULL DEFAULT 0, lastmod TEXT NOT NULL DEFAULT '', updated_at TEXT NOT NULL)");
    $columns=['body_format', 'og_title', 'og_description', 'og_image', 'profile_details'];
    if($db->getAttribute(PDO::ATTR_DRIVER_NAME)==='pgsql'){
        $existing=$db->query("SELECT column_name FROM information_schema.columns WHERE table_schema='hukuk' AND table_name='entries'")->fetchAll(PDO::FETCH_COLUMN);
        foreach($columns as $column)if(!in_array($column,$existing,true))$db->exec("ALTER TABLE entries ADD COLUMN IF NOT EXISTS $column TEXT NOT NULL DEFAULT '".($column==='body_format'?'text':'')."'");
        return;
    }
    $existing=array_column($db->query('PRAGMA table_info(entries)')->fetchAll(),'name');
    foreach($columns as $column)if(!in_array($column,$existing,true))$db->exec("ALTER TABLE entries ADD COLUMN $column TEXT NOT NULL DEFAULT '".($column==='body_format'?'text':'')."'");
}
