<?php
declare(strict_types=1);
function seed(PDO $db): void {
    $settings=[
        'brand'=>'Yurtdaş Hukuk','brand_subtitle'=>'AVUKATLIK & DANIŞMANLIK','brand_initial'=>'Y',
        'city'=>'Hatay','address'=>'A Plaza, Antakya, Küçükdalyan, Antakya/Hatay','phone'=>'0530 855 25 22','email'=>'','whatsapp'=>'905308552522','office_hours'=>'Hafta içi 09.00 – 18.00',
        'site_url'=>'','seo_title'=>'Yurtdaş Hukuk | Avukatlık ve Hukuki Danışmanlık','seo_description'=>'Yurtdaş Hukuk; bireyler ve kurumlar için avukatlık ve hukuki danışmanlık. Çalışma alanlarımızı ve hukuki yayınlarımızı inceleyin.',
        'accent_color'=>'#b59463','primary_color'=>'#142b36','logo'=>'', 'favicon'=>'',
        'hero_eyebrow'=>'YURTDAŞ HUKUK & DANIŞMANLIK','hero_title'=>'Hukukun rehberliğinde,\ngüvenle ileriye.','hero_text'=>'Her hukuki mesele, kendine özgü bir yaklaşımı hak eder. Haklarınızı anlamak, sürecinizi planlamak ve geleceğinizi güvenle şekillendirmek için yanınızdayız.',
        'hero_image'=>'/assets/images/justice-hero.jpg','hero_button'=>'Büromuzu tanıyın','hero_button_url'=>'/kurumsal','hero_secondary'=>'Çalışma alanlarımız','hero_secondary_url'=>'/calisma-alanlari',
        'hero_note'=>'HUKUKUN ÜSTÜNLÜĞÜ. MESLEKİ ÖZEN. GÜVEN.',
        'intro_eyebrow'=>'HUKUKA BAĞLILIK, İNSANA SAYGI','intro_title'=>'Her adımda açık iletişim.\nHer dosyada aynı özen.','intro_text'=>'Hukuki süreçlerin yalnızca evrak ve usullerden ibaret olmadığını biliyoruz. Her dosyanın arkasında bir insan, bir emek ve bir gelecek var.\nBireysel ve kurumsal ihtiyaçları dikkatle dinliyor; hukuki seçenekleri anlaşılır bir dille değerlendirerek süreci birlikte planlıyoruz.',
        'intro_image'=>'/assets/images/architecture.jpg','intro_label'=>'Yurtdaş Hukuk','intro_caption'=>'İlkelere bağlı. Çözüme odaklı.',
        'practice_eyebrow'=>'ÇALIŞMA ALANLARIMIZ','practice_title'=>'İhtiyacınıza uygun\nhukuki yaklaşım.','practice_text'=>'Bireysel ve kurumsal hukuki meselelerde, her alanın kendine özgü dinamiklerini dikkate alıyoruz.',
        'articles_eyebrow'=>'HUKUKİ YAYINLAR','articles_title'=>'Bilgi, doğru adımın başlangıcıdır.','articles_text'=>'Hukuki süreçleri anlamanıza yardımcı olacak yazılar, değerlendirmeler ve notlar.',
        'contact_eyebrow'=>'BİRLİKTE DEĞERLENDİRELİM','contact_title'=>'Hukuki süreciniz hakkında\nkonuşalım.','contact_text'=>'Görüşme talebinizi iletin; uygun zamanı birlikte planlayalım.','contact_button'=>'İletişime geçin',
        'footer_text'=>'Hukukun üstünlüğüne, mesleki özen ve açık iletişime dayanan bir çalışma anlayışı.','legal_notice'=>'Bu sitedeki içerikler genel bilgilendirme amacı taşır; hukuki görüş veya danışmanlık yerine geçmez. Her somut olay kendi koşullarında değerlendirilmelidir.',
        'linkedin'=>'','instagram'=>'','articles_per_page'=>'6','show_intro'=>'1','show_practices'=>'1','show_articles'=>'1','show_faq'=>'1','show_contact'=>'1','contact_enabled'=>'1','indexing'=>'0',
        'payment_enabled'=>'1','payment_label'=>'Online Ödeme','payment_url'=>'https://pos.mokaunited.com/CustomerPos/PaymentRequest?uppc=EJc8WsUNcxQ9C4Q0HHKh9w%3d%3d',
        'private_salt'=>bin2hex(random_bytes(32)),
    ];
    $settings=array_replace($settings,PUBLIC_SITE_COPY);
    $db->beginTransaction();
    $q=$db->prepare('INSERT INTO settings(key,value) VALUES(?,?)');foreach($settings as $k=>$v)$q->execute([$k,str_replace('\\n',"\n",$v)]);
    $add=function(string $type,string $title,string $slug,string $excerpt='',string $body='',string $category='',string $image='',int $order=0,string $link='')use($db){
        $q=$db->prepare('INSERT INTO entries(type,title,slug,excerpt,body,category,image,sort_order,link,status,published_at,updated_at,author) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)');
        $q->execute([$type,$title,$slug,$excerpt,$body,$category,$image,$order,$link,'published',date('Y-m-d H:i:s',strtotime('-'.($order+1).' days')),date('Y-m-d H:i:s'),'Yurtdaş Hukuk']);
    };
    foreach([['Ana Sayfa','/'],['Hakkımızda','/kurumsal'],['Çalışma Alanları','/calisma-alanlari'],['Makaleler','/makaleler'],['İletişim','/iletisim']] as $i=>$n)$add('menu',$n[0],slugify($n[0]),'','','','',$i,$n[1]);
    $practices=[
        ['Aile Hukuku','aile-hukuku','Aile ilişkilerinden doğan hukuki meselelerde özenli ve duyarlı bir yaklaşım.','users','Boşanma süreci ve aile ilişkileri|Velayet ve kişisel ilişki meseleleri|Malvarlığına ilişkin değerlendirmeler'],
        ['Ceza Hukuku','ceza-hukuku','Soruşturma ve kovuşturma süreçlerinde hakların korunması ve hukuki temsil.','scale','Soruşturma aşamasında hukuki yardım|Yargılama sürecinde temsil|Dosya ve delillerin değerlendirilmesi'],
        ['İş Hukuku','is-hukuku','Çalışma hayatında işçi ve işveren ilişkilerine yönelik hukuki danışmanlık.','briefcase','İş sözleşmelerinin incelenmesi|Çalışma ilişkilerinden doğan uyuşmazlıklar|İş ilişkisinin sona ermesi'],
        ['Ticaret & Şirketler Hukuku','ticaret-ve-sirketler-hukuku','Şirketlerin kuruluşundan ticari ilişkilerine kadar hukuki süreçlerin planlanması.','building','Şirket kuruluşu ve kurumsal işlemler|Ticari sözleşmelerin değerlendirilmesi|Ortaklık ilişkileri ve uyuşmazlıklar'],
        ['Gayrimenkul Hukuku','gayrimenkul-hukuku','Taşınmaz, kira ve mülkiyet ilişkilerinde hukuki inceleme ve uyuşmazlık yönetimi.','home','Tapu ve mülkiyet meseleleri|Kira ilişkilerinin değerlendirilmesi|Taşınmaz sözleşmelerinin incelenmesi'],
        ['Miras Hukuku','miras-hukuku','Miras ilişkileri ve malvarlığı planlamasında kapsamlı, dikkatli bir değerlendirme.','book','Mirasçılık ilişkilerinin değerlendirilmesi|Miras paylaşımına ilişkin uyuşmazlıklar|Miras planlaması ve belge inceleme'],
    ];
    foreach($practices as $i=>$p){$copy=PUBLIC_PRACTICE_COPY[$p[1]];$add('practice',$p[0],$p[1],$copy['excerpt'],public_practice_body($copy),$p[3],$copy['image'],$i);}
    $articles=[
        ['Hukuki görüşmeye nasıl hazırlanmalısınız?','hukuki-gorusmeye-hazirlik','İlk görüşmede ihtiyaç duyabileceğiniz belgeleri düzenlemek ve sorularınızı netleştirmek için kısa bir hazırlık rehberi.','Hukuki Süreçler','/assets/images/library.jpg',"## Görüşmenin amacını belirleyin\nBir hukuki görüşmeden önce, görüşmek istediğiniz konuyu birkaç cümleyle özetlemek yararlı olabilir. Neyi açıklığa kavuşturmak istediğinizi ve önceliklerinizi not edin.\n## Belgelerinizi düzenleyin\nSözleşme, yazışma, tebligat ve benzeri belgeleri tarih sırasına göre bir araya getirin. Belgenin tamamını ve varsa eklerini koruyun. Belgelerde değişiklik yapmadan asıllarını saklayın.\n- Olayların tarih sırasına göre kısa özeti\n- İlgili sözleşme ve yazışmalar\n- Yanıt bekleyen sorularınız\n## Süreleri ayrıca belirtin\nElinize ulaşan bir resmi bildirim veya tebligat varsa, teslim aldığınız tarihi avukatınızla paylaşın. Süreler somut olayın ve işlemin niteliğine göre değerlendirilir.\n## Sonraki adımları konuşun\nGörüşmenin sonunda, yapılabilecek işlemleri ve sizden beklenen belgeleri not alın. Çalışmanın kapsamını ve iletişim yöntemini netleştirin."],
        ['Sözleşme imzalamadan önce dikkatli okumanın önemi','sozlesme-inceleme','Tarafların beklentilerini açıkça ortaya koyan bir sözleşme için temel okuma ve değerlendirme notları.','Sözleşmeler','/assets/images/architecture.jpg',"## Metnin bütününü değerlendirin\nBir sözleşmeyi yalnızca başlığına veya özetine göre değerlendirmek, önemli ayrıntıların gözden kaçmasına yol açabilir. Ana metin, ekler ve atıf yapılan diğer belgeler birlikte okunmalıdır.\n## Belirsiz ifadeleri not edin\nTaraflar, işin kapsamı, teslim koşulları, ödeme ve iletişim yöntemleri anlaşılır biçimde tanımlanmalıdır. Anlamadığınız bir ifadeyi sormadan geçmeyin.\n- Tarafların kimlik ve iletişim bilgileri\n- Üstlenilen işin veya yükümlülüğün kapsamı\n- Tarihler, koşullar ve ek belgeler\n## Değişiklikleri takip edin\nGörüşmeler sırasında yapılan revizyonların son metne yansıyıp yansımadığını kontrol edin. Farklı sürümleri tarihleriyle saklamak, hangi metin üzerinde uzlaşıldığını takip etmeyi kolaylaştırır.\n## Hukuki inceleme\nSözleşmenin etkileri, tarafların durumuna ve işlemin niteliğine göre değişir. Somut metnin hukuki sonuçları için ayrı bir değerlendirme gerekir."],
        ['İş ilişkilerinde belgelerin düzenli tutulması','is-iliskilerinde-belgeler','Çalışma hayatına ilişkin kayıtların düzenli ve erişilebilir olmasına dair pratik bir bakış.','İş Hukuku','/assets/images/justice-hero.jpg',"## Düzenli bir kayıt alışkanlığı\nÇalışma ilişkisi boyunca oluşturulan belgeler, tarafların hangi konularda ve ne zaman iletişim kurduğunu anlamaya yardımcı olur. Sözleşmeleri ve size iletilen yazılı bildirimleri düzenli biçimde saklamak yararlıdır.\n## Tarih sırası ve bütünlük\nBelgeyi ait olduğu dönemle ilişkilendirin; eklerini ana belgeden ayırmamaya dikkat edin. Dijital belgelerin orijinal biçimini koruyun.\n## Gizlilik\nBelgelere erişimi sınırlayın. Başkalarına ait kişisel verileri veya kurum içi bilgileri gereksiz biçimde paylaşmayın.\n## Hukuki değerlendirme\nBir belgenin hukuki niteliği ve kullanılabilirliği somut olayın koşullarına bağlıdır. Bir uyuşmazlık durumunda belgelerin tamamını avukatınızla birlikte değerlendirin."],
        ['Taşınmaz işlemlerinde görüşme öncesi hazırlık','tasinmaz-islemleri-hazirlik','Taşınmazla ilgili hukuki bir görüşme öncesinde konuyu ve belgeleri bir araya getirmek.','Gayrimenkul Hukuku','/assets/images/architecture.jpg',"## Konuyu netleştirin\nSatış, kira, kullanım veya mülkiyetle ilgili bir meseleyi değerlendirirken, taşınmazın tanımı ve ilişkinin geçmişi önemlidir. Hangi soruya yanıt aradığınızı görüşme öncesinde not edin.\n## Belgeleri bir araya getirin\nElinizde bulunan sözleşmeler, yazışmalar ve resmi bildirimleri tarih sırasıyla düzenleyin. Eksik olduğunu düşündüğünüz belgeleri ayrıca listeleyin.\n## Somut inceleme\nTaşınmazın durumu, tarafların sıfatları ve işlemin niteliği değerlendirmeyi etkiler. Genel bir yazı, belirli bir taşınmaza ilişkin belge ve kayıt incelemesinin yerini tutmaz."],
        ['Aile hukukunda iletişim ve mahremiyet','aile-hukukunda-mahremiyet','Aile ilişkilerine dair bir hukuki süreçte kişisel bilgilerin özenle ele alınması.','Aile Hukuku','/assets/images/library.jpg',"## Özenli iletişim\nAile ilişkilerinden doğan meseleler kişisel ve duygusal yönler taşır. Hukuki görüşmede, olayları mümkün olduğunca açık ve tarih sırasıyla paylaşmak konunun anlaşılmasına yardımcı olur.\n## Bilgi paylaşımında dikkat\nKişisel belgeleri paylaşmadan önce hangi bilginin inceleme için gerekli olduğunu belirleyin. Hassas içerikleri herkese açık kanallarda yayınlamayın.\n## Sürecin planlanması\nSorularınızı, önceliklerinizi ve endişelerinizi not edin. Hukuki seçenekler ve sonraki adımlar, somut dosyanın koşulları üzerinden değerlendirilir."],
        ['Kurumsal hukuki danışmanlıkta düzenli iletişim','kurumsal-hukuki-danismanlik','Şirket içi süreçler ile hukuki değerlendirme arasında açık bir iletişim düzeni kurmak.','Ticaret Hukuku','/assets/images/justice-hero.jpg',"## İhtiyaçların belirlenmesi\nKurumsal hukuki danışmanlıkta, şirketin faaliyetleri ve iş süreçlerinin anlaşılması başlangıç noktasıdır. Sorumlu kişilerin ve öncelikli konuların belirlenmesi iletişimi kolaylaştırır.\n## Belgelerin güncel tutulması\nSözleşme sürümleri, kararlar ve yazışmalar düzenli biçimde saklanmalıdır. Bir işlemin hangi aşamada olduğunun açık olması değerlendirmeye yardımcı olur.\n## Planlı değerlendirme\nYeni bir ticari ilişki veya işlem öncesinde belge ve beklentileri paylaşmak, hukuki incelemeye zaman ayrılmasını sağlar. Danışmanlığın kapsamı taraflar arasında ayrıca belirlenir."],
    ];
    foreach($articles as $i=>$a)$add('article',$a[0],$a[1],$a[2],$a[5],$a[3],$a[4],$i);
    $add('page','Hakkımızda','kurumsal',PUBLIC_CORPORATE_EXCERPT,PUBLIC_CORPORATE_BODY,'','/assets/images/architecture.jpg');
    $add('page','Kişisel Verilerin Korunması','kvkk','İletişim formuna ilişkin aydınlatma metni taslağı.',"## Aydınlatma metni hakkında\nBu sayfa büroya ait gerçek bilgilerle tamamlanması gereken bir taslaktır. Veri sorumlusunun kimliği ve başvuru kanalı, veri işleme amaçları ve hukuki sebepleri, aktarım yapılabilecek alıcılar, toplama yöntemi ve ilgili kişi hakları büroya özgü olarak belirtilmelidir.\n## Bu sitenin iletişim formu\nFormda ad soyad, e-posta, isteğe bağlı telefon, konu ve mesaj alanları bulunur. İletilen başvuru, site yönetim panelinde tutulur. Form üzerinden dosya yüklenmez.\n## Başvuru ve bilgi\nKişisel verilerinize ilişkin sorular için büronun iletişim kanallarını kullanabilirsiniz.\nAydınlatma yükümlülüğü hakkında [Kişisel Verileri Koruma Kurumunun açıklamalarını](https://www.kvkk.gov.tr/Icerik/2033/Aydinlatma-Yukumlulugu-) inceleyebilirsiniz.");
    $add('page','Çerez Politikası','cerez-politikasi','Sitenin çalışması için kullanılan çerezler ve harici hizmetler hakkında.',PUBLIC_COOKIE_BODY);
    $add('page','Yasal Bilgilendirme','yasal-bilgilendirme','İçeriklerin kullanımına ilişkin açıklamalar.',"## Bilgilendirme amacı\nBu sitedeki yazılar genel bilgi amacıyla hazırlanmıştır. Belirli bir olaya ilişkin hukuki görüş veya danışmanlık niteliğinde değildir.\n## Somut olayın değerlendirilmesi\nHukuki sonuçlar olayın koşullarına, belgelere ve yürürlükteki düzenlemelere göre değişebilir. Bir işlem yapmadan önce somut durumunuzun ayrıca değerlendirilmesi gerekir.\n## İletişim\nİletişim formunun gönderilmesi tek başına avukatlık ilişkisi kurmaz. Çalışmanın kapsamı ve koşulları ayrıca belirlenir.");
    foreach([
        ['İlk görüşme için nasıl randevu alabilirim?',PUBLIC_APPOINTMENT_ANSWER],
        ['Görüşmeye hangi belgeleri getirmeliyim?','Konuyla ilgili sözleşme, yazışma, tebligat ve diğer belgeler ile olayların kısa bir zaman çizelgesini hazırlayabilirsiniz. İhtiyaç duyulan belgeler konuya göre değişir.'],
        ['Hukuki sürecim hakkında nasıl bilgi alırım?','Çalışmanın başında iletişim yöntemi ve sürecin kapsamı belirlenir. Gelişmeler ve sizden beklenen belgeler bu iletişim düzeni içinde paylaşılır.'],
        ['Sitedeki yazılar hukuki danışmanlık yerine geçer mi?','Hayır. Yayınlarımız genel bilgilendirme amacı taşır. Her mesele kendi koşulları içinde, ilgili belgeler ve güncel düzenlemelerle birlikte değerlendirilmelidir.'],
    ] as $i=>$f)$add('faq',$f[0],'soru-'.($i+1),'',$f[1],'','',$i);
    $db->commit();
}
