<?php
declare(strict_types=1);
function theme_preview(): void { ?>
<div class="theme-tools"><p class="a-field-hint">Hazır palet seçebilir veya aşağıdaki renkleri tek tek değiştirebilirsiniz. Palet seçimi kaydetmeden siteyi değiştirmez.</p><div class="palette-buttons"><button type="button" class="a-button secondary small" data-palette="navy">Kurumsal lacivert</button><button type="button" class="a-button secondary small" data-palette="editorial">Editoryal yeşil</button><button type="button" class="a-button secondary small" data-palette="warm">Sıcak klasik</button><button type="button" class="a-button secondary small" data-palette="green">Orman yeşili</button></div><div class="theme-preview" aria-label="Tema renk önizlemesi"><div class="preview-header">Büro adı <span>Ana sayfa · Çalışma alanları · İletişim</span></div><div class="preview-hero" style="--preview-image:url('<?=e(safe_image(setting('hero_image')))?>')"><small>HUKUK & DANIŞMANLIK</small><h3>Her ayrıntıda özen.</h3><span class="preview-button">Görüşme talebi →</span></div><div class="preview-body"><div class="preview-card"><strong>Çalışma alanlarımız</strong><p>Başlık, metin, kart ve buton renklerinin birlikte görünümü.</p><span class="preview-link">Detaylı bilgi →</span></div></div><div class="preview-footer">Büro adı · İletişim bilgileri</div></div><p class="theme-contrast a-field-hint" role="status"></p></div>
<?php }
function theme_setting_field(string $key,string $label,string $kind,string $value): bool {
    if($kind==='select'):?><label><?=e($label)?><select name="<?=e($key)?>"><?php foreach(THEME_OPTIONS[$key] as $v=>$text):?><option value="<?=e($v)?>" <?=$value===$v?'selected':''?>><?=e($text)?></option><?php endforeach;?></select></label><?php return true;
    elseif($kind==='section-order'):$order=array_values(array_unique(array_merge(array_intersect(($value===setting('home_section_order')?home_sections():array_map('trim',explode(',',$value))),array_keys(HOME_SECTIONS)),array_keys(HOME_SECTIONS))));?><div class="wide section-order"><strong><?=e($label)?></strong><input type="hidden" name="<?=e($key)?>" value="<?=e(implode(',',$order))?>"><ol><?php foreach($order as $part):?><li data-section="<?=e($part)?>"><span><?=e(HOME_SECTIONS[$part])?></span><button type="button" data-move="up" aria-label="<?=e(HOME_SECTIONS[$part])?> yukarı taşı">↑</button><button type="button" data-move="down" aria-label="<?=e(HOME_SECTIONS[$part])?> aşağı taşı">↓</button></li><?php endforeach;?></ol><span class="order-status a-field-hint" role="status"></span></div><?php return true;
    elseif($kind==='color'):?><label><?=e($label)?><div class="color-control"><input type="color" name="<?=e($key)?>" value="<?=e($value)?>"><input type="text" class="color-hex" aria-label="<?=e($label)?> HEX kodu" value="<?=e($value)?>" pattern="#[a-fA-F0-9]{6}" maxlength="7" required></div></label><?php return true;
    elseif($kind==='number'&&(isset(THEME_NUMBERS[$key])||isset(SITE_CONTROL_NUMBERS[$key]))):[$min,$max,$default]=THEME_NUMBERS[$key]??SITE_CONTROL_NUMBERS[$key];?><label><?=e($label)?><input type="number" name="<?=e($key)?>" value="<?=e($value===''?$default:$value)?>" min="<?=$min?>" max="<?=$max?>" required></label><?php return true;
    endif;return false;
}
