<?php declare(strict_types=1);
$candidates=sitemap_candidates();$policies=seo_url_policies();$included=array_column(sitemap_rows(),null,'path');$search=query('q');
function sitemap_editor(string $path,array $page,array $policy): void { ?>
<form class="sitemap-form a-form-card" action="/admin/action.php" method="post" data-dirty-form><?=csrf_field()?><input type="hidden" name="action" value="save-sitemap-url"><input type="hidden" name="path" value="<?=e($path)?>"><div class="seo-form-grid"><div class="seo-fields"><label class="a-toggle"><span><strong>Site haritasına ekle</strong></span><input type="checkbox" name="sitemap_enabled" value="1" <?=($policy['sitemap_enabled']??1)?'checked':''?>><span class="toggle-track"></span></label><label class="a-toggle"><span><strong>Arama sonuçlarında gösterme (noindex)</strong></span><input type="checkbox" name="noindex" value="1" <?=($policy['noindex']??$page['noindex'])?'checked':''?>><span class="toggle-track"></span></label></div><div class="seo-fields"><label>Son değişiklik tarihi (isteğe bağlı)<input type="date" name="lastmod" max="<?=date('Y-m-d')?>" value="<?=e($policy['lastmod']??'')?>"></label><small class="a-field-hint">Boş bırakınca gerçek içerik güncelleme tarihi kullanılır. Otomatik tarih: <?=e($page['lastmod'])?>. Noindex sayfalar haritadan çıkarılır.</small></div></div><button class="a-button" type="submit">Kaydet</button></form>
<?php }
?>
<div class="a-page-heading"><div><span class="a-overline">SEO YÖNETİMİ</span><h1>Site haritası ve görünürlük</h1><p>Yayınlanmış sayfaları ekleyin, çıkarın ve görünürlüklerini düzenleyin. Yeni içerikler yayımlandığında otomatik eklenir.</p></div><a class="a-button secondary" href="/sitemap.xml" target="_blank" rel="noopener">XML’i görüntüle</a></div>
<section class="a-card a-form-card"><form action="/admin/action.php" method="post"><?=csrf_field()?><input type="hidden" name="action" value="toggle-sitemap"><label class="a-toggle"><span><strong>XML site haritasını yayımla</strong><small>Kapalıyken /sitemap.xml yayınlanmaz ve robots.txt içinden kaldırılır.</small></span><input type="checkbox" name="sitemap_enabled" value="1" <?=setting('sitemap_enabled','1')==='1'?'checked':''?>><span class="toggle-track"></span></label><button class="a-button secondary" type="submit">Yayın durumunu kaydet</button></form><p class="a-field-hint"><?=count($included)?> adres haritada. Genel dizine ekleme: <?=setting('indexing')==='1'?'Açık':'Kapalı (yayın hazırlığı)'?>. <a href="/admin/?view=settings&amp;group=seo">Genel SEO ayarları</a></p></section>
<section class="a-card"><h2>Haritaya sayfa ekle / düzenle</h2><form class="a-form-card" action="/admin/action.php" method="post"><?=csrf_field()?><input type="hidden" name="action" value="save-sitemap-url"><input type="hidden" name="sitemap_enabled" value="1"><input type="hidden" name="noindex" value="0"><label>Yayınlanmış sayfa<select name="path" required><?php foreach($candidates as $path=>$page):?><option value="<?=e($path)?>"><?=e($page['title'].' — '.$path)?></option><?php endforeach;?></select></label><input type="hidden" name="lastmod" value=""><button class="a-button secondary" type="submit">Haritaya ekle</button></form><p class="a-field-hint">Bu işlem sayfanın noindex ayarını kapatır. Taslaklar, arşivlenen içerikler, gelecek tarihli yayınlar ve yönlendirme kaynakları eklenmez.</p></section>
<section class="a-card"><form method="get" class="a-filters"><input type="hidden" name="view" value="sitemap"><div class="a-search"><?=icon('search')?><input type="search" name="q" placeholder="Sayfa veya adreste ara" aria-label="Site haritasında ara" value="<?=e($search)?>"></div><button class="a-button secondary" type="submit">Ara</button></form><div class="seo-static-list"><?php foreach($candidates as $path=>$page):if($search&&mb_stripos($path.' '.$page['title'],$search)===false)continue;$policy=$policies[$path]??[];?><details class="seo-item"><summary><span class="seo-item-title"><strong><?=e($page['title'])?></strong><small><?=e($path)?></small></span><span class="badge <?=isset($included[$path])?'published':'draft'?>"><?=isset($included[$path])?'Haritada':'Harita dışında'?></span></summary><div class="seo-item-body"><?php sitemap_editor($path,$page,$policy);?><?php if($policy):?><form action="/admin/action.php" method="post"><?=csrf_field()?><input type="hidden" name="action" value="reset-sitemap-url"><input type="hidden" name="path" value="<?=e($path)?>"><button class="a-button secondary" type="submit">Özel harita ayarını kaldır</button></form><?php endif;?></div></details><?php endforeach;?></div></section>
<?php $inactive=array_diff_key($policies,$candidates);if($inactive):?><section class="a-card"><h2>Yayın dışı adres ayarları</h2><p class="a-muted">Bu adresler artık yayında olmadığı için haritaya eklenmez.</p><?php foreach($inactive as $path=>$row):?><form class="revision-row" action="/admin/action.php" method="post"><?=csrf_field()?><input type="hidden" name="action" value="reset-sitemap-url"><input type="hidden" name="path" value="<?=e($path)?>"><span><?=e($path)?></span><button class="a-button secondary small" type="submit">Ayarı sil</button></form><?php endforeach;?></section><?php endif;?>
