<?php declare(strict_types=1);
$redirectRows=db()->query('SELECT * FROM url_redirects ORDER BY source_path')->fetchAll();
function redirect_editor(array $row): void { ?>
<form class="a-form-card redirect-form" action="/admin/action.php" method="post" data-dirty-form>
<?=csrf_field()?><input type="hidden" name="action" value="save-redirect"><input type="hidden" name="id" value="<?=e($row['id']??'')?>"><input type="hidden" name="original_updated_at" value="<?=e($row['updated_at']??'')?>">
<div class="seo-form-grid"><div class="seo-fields"><label>Eski / kaynak adres<input name="source_path" required maxlength="500" placeholder="/eski-sayfa" value="<?=e($row['source_path']??'')?>"></label><label>Yeni / hedef adres<input name="target_path" required maxlength="500" placeholder="/calisma-alanlari" value="<?=e($row['target_path']??'')?>"></label></div><div class="seo-fields"><label>Yönlendirme türü<select name="status_code"><option value="301" <?=($row['status_code']??301)==301?'selected':''?>>301 — kalıcı</option><option value="302" <?=($row['status_code']??301)==302?'selected':''?>>302 — geçici</option></select></label><label class="a-toggle"><span><strong>Yönlendirme aktif</strong></span><input type="checkbox" name="enabled" value="1" <?=($row['enabled']??1)?'checked':''?>><span class="toggle-track"></span></label></div></div><button class="a-button" type="submit">Yönlendirmeyi kaydet</button></form>
<?php }
?>
<div class="a-page-heading"><div><span class="a-overline">SEO YÖNETİMİ</span><h1>301 / 302 yönlendirmeler</h1><p>Site içindeki eski adresleri yeni adreslere taşıyın. Adresleri / ile başlayan yol olarak yazın.</p></div><a class="a-button secondary" href="/admin/?view=sitemap">Site haritası</a></div>
<section class="a-card"><div class="a-card-heading"><h2>Yeni yönlendirme ekle</h2></div><?php redirect_editor([]);?><p class="a-field-hint">Kalıcı adres değişimlerinde 301; geçici taşımada 302 kullanın. Ana sayfa ve yönetim adresleri kaynak olamaz. Aynı adrese ve döngüye yol açan kayıtlar engellenir.</p></section>
<section class="a-card"><div class="a-card-heading"><h2>Kayıtlı yönlendirmeler</h2><span><?=count($redirectRows)?> kayıt</span></div><div class="seo-static-list"><?php foreach($redirectRows as $row):?><details class="seo-item"><summary><span class="seo-item-title"><strong><?=e($row['source_path'])?></strong><small>→ <?=e($row['target_path'])?></small></span><span class="badge <?=$row['enabled']?'published':'draft'?>"><?=$row['status_code']?> · <?=$row['enabled']?'Aktif':'Kapalı'?></span></summary><div class="seo-item-body"><?php redirect_editor($row);?><form action="/admin/action.php" method="post" data-confirm="Bu yönlendirme silinsin mi? Sayfa içeriği silinmez."><?=csrf_field()?><input type="hidden" name="action" value="delete-redirect"><input type="hidden" name="id" value="<?=$row['id']?>"><input type="hidden" name="original_updated_at" value="<?=e($row['updated_at'])?>"><button class="a-button secondary danger" type="submit">Yönlendirmeyi sil</button></form></div></details><?php endforeach;if(!$redirectRows):?><p class="a-muted">Henüz elle eklenmiş yönlendirme yok.</p><?php endif;?></div></section>
<section class="a-card"><h2>İçerik adresi değiştiğinde</h2><p class="a-muted">Makale veya çalışma alanının bağlantı adını değiştirince eski adresten yeni adrese 301 otomatik eklenir. Bu işlemi ayrıca burada eklemeniz gerekmez.</p><?php $automatic=db()->query('SELECT r.type,r.slug AS old_slug,e.* FROM entry_redirects r JOIN entries e ON e.id=r.entry_id ORDER BY r.type,r.slug')->fetchAll();?><div class="table-scroll"><table class="a-table"><thead><tr><th>İçerik</th><th>Eski bağlantı adı</th><th>Hedef</th></tr></thead><tbody><?php foreach($automatic as $r):?><tr><td><?=e($r['title'])?></td><td><?=e($r['old_slug'])?></td><td><?=e(entry_url($r))?></td></tr><?php endforeach;?></tbody></table></div><p class="a-field-hint">Otomatik yönlendirmeler yalnızca hedef içerik yayındayken çalışır.</p></section>
