<?php declare(strict_types=1); ?>
<section class="juris-hero" aria-labelledby="hero-title">
    <div class="juris-hero-media"><img class="hero-image is-active" data-parallax="background" src="<?=e(safe_image(setting('hero_image')))?>" alt="<?=e(setting('hero_image_alt'))?>" width="1536" height="1024" fetchpriority="high"></div>
    <div class="juris-hero-shade" aria-hidden="true"></div>
    <div class="container juris-hero-content">
        <div class="juris-hero-copy">
            <span class="hero-identity-mark" data-parallax="mark" aria-hidden="true"><img src="<?=e(safe_image(setting('logo_mark')?:setting('logo')?:'/assets/images/yurtdas-seal-v2.svg'))?>" alt="" width="80" height="88"></span>
            <span class="eyebrow"><?=e(setting('hero_eyebrow'))?></span>
            <h1 id="hero-title"><?=nl2br(e(setting('hero_title')))?></h1>
            <div class="juris-hero-lead"><?=rich_text(setting('hero_text'))?></div>
            <div class="juris-hero-actions"><a class="button" href="<?=e(safe_url(setting('hero_button_url')))?>"><?=e(setting('hero_button'))?> <?=icon('arrow')?></a><a class="button button-glass" href="<?=e(safe_url(setting('hero_secondary_url')))?>"><?=e(setting('hero_secondary'))?> <?=icon('arrow')?></a></div>
            <?php if(setting('hero_note')):?><p class="hero-note"><?=e(setting('hero_note'))?></p><?php endif;?>
        </div>
    </div>
</section>
<?php if(setting('show_home_contacts')==='1'): ?>
<aside class="home-contact-strip" aria-label="<?=e(ui('contact_info_title'))?>">
    <div class="container home-contact-items">
        <?php if(setting('address')):?><a class="home-contact-item home-contact-address" href="<?=e(map_open_url())?>" target="_blank" rel="noopener noreferrer"><?=icon('pin')?><span><strong><?=e(ui('contact_address_label'))?></strong><span><?=e(setting('address'))?></span></span><?=icon('arrow-up')?></a><?php endif;?>
        <?php if(setting('phone')):?><a class="home-contact-item" href="<?=e(phone_url(setting('phone')))?>"><?=icon('phone')?><span><strong><?=e(ui('contact_phone_label'))?></strong><span><?=e(setting('phone'))?></span></span></a><?php endif;?>
        <?php if(setting('email')):?><a class="home-contact-item" href="mailto:<?=e(setting('email'))?>"><?=icon('mail')?><span><strong><?=e(ui('contact_email_label'))?></strong><span><?=e(setting('email'))?></span></span></a><?php elseif(setting('office_hours')):?><div class="home-contact-item"><?=icon('clock')?><span><strong><?=e(ui('contact_hours_label'))?></strong><span><?=e(setting('office_hours'))?></span></span></div><?php endif;?>
    </div>
</aside>
<?php endif; ?>
<div id="ana-icerik"></div>
<?php foreach(home_sections() as $section):if(setting('show_'.$section)!=='1')continue; ?>
<?php if($section==='home_profile'): home_profile(); ?>
<?php elseif($section==='home_consultation'): home_consultation(); ?>
<?php elseif($section==='home_map'): home_map(); ?>
<?php elseif($section==='office'): ?>
<section class="juris-ribbon" data-home-section="office"><div class="container juris-ribbon-inner"><div><span class="eyebrow"><?=e(setting('office_eyebrow'))?></span><h2><?=nl2br(e(setting('office_title')))?></h2><div class="office-text"><?=rich_text(setting('office_text'))?></div></div><a class="button button-outline" href="/kurumsal"><?=e(ui('office_about'))?> <?=icon('arrow')?></a></div></section>
<?php elseif($section==='intro'): ?>
<section class="section introduction juris-about" id="yaklasim" data-home-section="intro">
    <div class="container juris-about-inner">
        <div class="juris-about-copy"><span class="eyebrow"><?=e(setting('intro_eyebrow'))?></span><h2><?=nl2br(e(setting('intro_title')))?></h2><div class="intro-text"><?=rich_text(setting('intro_text'))?></div><a class="text-link" href="<?=e(safe_url(setting('intro_link_url')))?>"><?=e(ui('intro_link'))?> <?=icon('arrow')?></a></div>
        <figure class="juris-about-visual"><img data-parallax="foreground" src="<?=e(safe_image(setting('intro_image')))?>" alt="<?=e(setting('intro_image_alt'))?>" width="600" height="480" loading="lazy"></figure>
    </div>
</section>
<?php elseif($section==='principles'): ?>
<section class="juris-values" data-home-section="principles" aria-label="<?=e(ui('values_label'))?>"><div class="container"><div class="juris-values-heading"><span class="eyebrow"><?=e(ui('values_label'))?></span></div><div class="juris-values-grid"><?php foreach(['shield','scale','users','phone'] as $i=>$symbol):?><div class="juris-value"><span class="juris-value-icon"><?=icon($symbol)?></span><h2><?=e(ui('principle_'.($i+1).'_title'))?></h2><p><?=e(ui('principle_'.($i+1).'_text'))?></p></div><?php endforeach;?></div></div></section>
<?php elseif($section==='practices'): $practices=array_slice(entries('practice'),0,(int)setting('home_practice_count','6'));if(!$practices)continue; ?>
<section class="section practices-section juris-practices" data-home-section="practices"><div class="container"><div class="juris-section-heading"><span class="eyebrow"><?=e(setting('practice_eyebrow'))?></span><h2><?=nl2br(e(setting('practice_title')))?></h2><div class="practice-text"><?=rich_text(setting('practice_text'))?></div></div><div class="service-grid"><?php foreach($practices as $i=>$p)service_card($p,$i);?></div><div class="section-tail"><a class="button button-outline" href="/calisma-alanlari"><?=e(ui('all_practices'))?> <?=icon('arrow')?></a></div></div></section>
<?php elseif($section==='approach'): ?>
<section class="section approach-section juris-approach" data-home-section="approach"><div class="container juris-approach-inner"><figure class="juris-approach-visual"><img src="<?=e(safe_image(setting('approach_image')))?>" alt="<?=e(setting('approach_image_alt'))?>" width="740" height="640" loading="lazy"></figure><div class="juris-approach-copy"><span class="eyebrow"><?=e(setting('approach_eyebrow'))?></span><h2><?=nl2br(e(setting('approach_title')))?></h2><div class="juris-approach-text"><?=text_markup(setting('approach_text'))?></div><a class="button button-outline" href="<?=e(safe_url(setting('contact_button_url')))?>"><?=e(setting('contact_button'))?> <?=icon('arrow')?></a></div></div></section>
<?php elseif($section==='articles'): $articles=array_slice(entries('article'),0,(int)setting('home_article_count','6'));if(!$articles)continue; ?>
<section class="section articles-section" data-home-section="articles"><div class="container"><div class="section-heading"><div><span class="eyebrow"><?=e(setting('articles_eyebrow'))?></span><h2><?=e(setting('articles_title'))?></h2><p><?=e(setting('articles_text'))?></p></div><a class="text-link" href="/makaleler"><?=e(ui('all_articles'))?> <?=icon('arrow')?></a></div><?php if(setting('home_articles_layout')==='editorial'):?><div class="journal-grid"><div class="journal-feature"><?php article_card(array_shift($articles));?></div><div class="journal-list"><?php foreach($articles as $a):?><article class="journal-row"><a class="journal-thumb" href="<?=e(entry_url($a))?>" tabindex="-1" aria-hidden="true"><img src="<?=e(safe_image($a['image']))?>" alt="" width="160" height="120" loading="lazy"></a><div><span class="article-category"><?=e($a['category'])?></span><h3><a href="<?=e(entry_url($a))?>"><?=e($a['title'])?></a></h3><?php $author=author_of($a);?><span class="journal-author"><?=e(ui('author_label'))?> <?php if($author):?><a href="<?=e(entry_url($author))?>"><?=e($author['title'])?></a><?php else:?><?=e($a['author']?:setting('brand'))?><?php endif;?></span><time datetime="<?=e(substr($a['published_at'],0,10))?>"><?=date_tr($a['published_at'])?></time></div></article><?php endforeach;?></div></div><?php else:?><div class="article-grid"><?php foreach($articles as $a)article_card($a);?></div><?php endif;?></div></section>
<?php elseif($section==='faq'): ?>
<section class="section faq-section" id="sik-sorulan-sorular" data-home-section="faq"><div class="container faq-grid"><div><span class="eyebrow"><?=e(ui('faq_eyebrow'))?></span><h2><?=e(ui('faq_title'))?></h2><p><?=e(ui('faq_text'))?></p><a class="text-link" href="/sikca-sorulan-sorular"><?=e(ui('all_faq'))?> <?=icon('arrow')?></a></div><?php faq_list();?></div></section>
<?php elseif($section==='contact'): ?>
<section class="juris-contact" data-home-section="contact" aria-labelledby="juris-contact-title"><div class="juris-contact-form" id="iletisim-formu"><div class="juris-contact-inner"><span class="eyebrow"><?=e(setting('contact_eyebrow'))?></span><h2 id="juris-contact-title"><?=nl2br(e(setting('contact_title')))?></h2><div class="contact-text"><?=rich_text(setting('contact_text'))?></div><?php if(contact_form_available()):?><form action="/iletisim#iletisim-formu" method="post" class="contact-form"><?=csrf_field()?><div class="form-grid"><label><?=e(ui('form_name'))?> <span>*</span><input name="name" autocomplete="name" required minlength="2" maxlength="100"></label><label><?=e(ui('form_email'))?> <span>*</span><input type="email" name="email" autocomplete="email" required maxlength="190"></label><label><?=e(ui('form_phone'))?><input type="tel" name="phone" autocomplete="tel" maxlength="30"></label><label><?=e(ui('form_subject'))?> <span>*</span><select name="subject" required><option value=""><?=e(ui('form_choose'))?></option><?php foreach(array_merge(array_column(entries('practice'),'title'),[ui('contact_other_subject')]) as $s):?><option><?=e($s)?></option><?php endforeach;?></select></label></div><label><?=e(ui('form_message'))?> <span>*</span><textarea name="message" rows="4" minlength="15" maxlength="5000" required></textarea></label><div class="honeypot" aria-hidden="true"><label>Web siteniz<input name="website" tabindex="-1" autocomplete="off"></label></div><p class="form-privacy"><a href="/sayfa/kvkk" target="_blank" rel="noopener"><?=e(ui('contact_notice_agreement'))?></a></p><button class="button" type="submit"><?=e(ui('contact_form_button'))?> <?=icon('arrow')?></button><p class="form-note"><?=e(ui('contact_form_note'))?></p></form><?php else:?><a class="button" href="/iletisim"><?=e(setting('contact_button'))?> <?=icon('arrow')?></a><?php endif;?></div></div><div class="juris-contact-info"><div class="juris-contact-inner"><span class="eyebrow"><?=e(setting('brand_subtitle'))?></span><h2><?=e(ui('contact_info_title'))?></h2><p><?=e(ui('contact_info_text'))?></p><dl><div><dt><?=e(ui('contact_address_label'))?></dt><dd><?=nl2br(e(setting('address')))?></dd></div><?php if(setting('email')):?><div><dt><?=e(ui('contact_email_label'))?></dt><dd><a href="mailto:<?=e(setting('email'))?>"><?=e(setting('email'))?></a></dd></div><?php endif;if(setting('phone')):?><div><dt><?=e(ui('contact_phone_label'))?></dt><dd><a href="tel:<?=e(preg_replace('/[^+0-9]/','',setting('phone')))?>"><?=e(setting('phone'))?></a></dd></div><?php endif;?><div><dt><?=e(ui('contact_hours_label'))?></dt><dd><?=e(setting('office_hours'))?></dd></div></dl><a class="text-link" href="/iletisim"><?=e(setting('contact_button'))?> <?=icon('arrow')?></a></div></div></section>
<?php endif;endforeach; ?>
